package com.example.apptienda

enum class RequestCode(val value: Int) {
    GO_TO_LOGIN_FROM_MAIN_ACTIVITY(1),
    GO_TO_REGISTER_FROM_LOGIN_ACTIVITY(2),
    GO_TO_LOGIN_FROM_REGISTER_ACTIVITY(3),
    GO_TO_SUMMARY_ORDER_FROM_PRODUCT_DETAIL_ACTIVITY(4)
}