package com.example.apptienda

enum class RequestCode(val value: Int) {
    GO_TO_LOGIN_FROM_MAIN_ACTIVITY(1),
    GO_TO_REGISTER_FROM_LOGIN_ACTIVITY(2),
    GO_TO_LOGIN_FROM_REGISTER_ACTIVITY(3),
    GO_TO_SUMMARY_ORDER_FROM_PRODUCT_DETAIL_ACTIVITY(4),
    GO_TO_CREATE_PRODUCT_FROM_PRODUCT_FRAG (5),
    REQUEST_TAKE_PHOTO (6),
    GO_TO_CREATE_PRODUCT_FROM_EDIT_PRODUCT (7)
}